// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkO5EJv8u-5d9Ie9pNcM-unMyYxgZpyhQ',
    appId: '1:1029079198473:web:ad5913dd964685b37f81d8',
    messagingSenderId: '1029079198473',
    projectId: 'pantua-ecommerce-app',
    authDomain: 'pantua-ecommerce-app.firebaseapp.com',
    storageBucket: 'pantua-ecommerce-app.firebasestorage.app',
    measurementId: 'G-K1LML51WJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOriVBCiLPCezXzzosEdDcpeJbH13_E4',
    appId: '1:1029079198473:android:dbef03c84315d0237f81d8',
    messagingSenderId: '1029079198473',
    projectId: 'pantua-ecommerce-app',
    storageBucket: 'pantua-ecommerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxWzO6pyCjKWkLTXNAzb8bqsaCccXmMoI',
    appId: '1:1029079198473:ios:75cdaacecfb34c147f81d8',
    messagingSenderId: '1029079198473',
    projectId: 'pantua-ecommerce-app',
    storageBucket: 'pantua-ecommerce-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxWzO6pyCjKWkLTXNAzb8bqsaCccXmMoI',
    appId: '1:1029079198473:ios:75cdaacecfb34c147f81d8',
    messagingSenderId: '1029079198473',
    projectId: 'pantua-ecommerce-app',
    storageBucket: 'pantua-ecommerce-app.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkO5EJv8u-5d9Ie9pNcM-unMyYxgZpyhQ',
    appId: '1:1029079198473:web:f647a3523d283cd67f81d8',
    messagingSenderId: '1029079198473',
    projectId: 'pantua-ecommerce-app',
    authDomain: 'pantua-ecommerce-app.firebaseapp.com',
    storageBucket: 'pantua-ecommerce-app.firebasestorage.app',
    measurementId: 'G-M7TW39GPQH',
  );

}